/**
 * generated by Xtext
 */
package org.jnario.spec.formatting2;

import org.jnario.formatter.JnarioFormatter;

@SuppressWarnings("all")
public class SpecFormatter extends JnarioFormatter {
}
