/**
 * generated by Xtext
 */
package org.jnario.feature.formatting2;

import org.eclipse.xtext.xbase.annotations.formatting2.XbaseWithAnnotationsFormatter;

@SuppressWarnings("all")
public class FeatureFormatter extends XbaseWithAnnotationsFormatter {
}
