/*
 * generated by Xtext
 */
package org.jnario.xbase.richstring.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class XbaseWithRichstringProposalProvider extends org.jnario.xbase.richstring.ui.contentassist.AbstractXbaseWithRichstringProposalProvider {

}
