/*
 * generated by Xtext
 */
package org.jnario.xbase.richstring;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;
import org.jnario.xbase.richstring.conversion.XbaseWithRichstringValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XbaseWithRichstringRuntimeModule extends org.jnario.xbase.richstring.AbstractXbaseWithRichstringRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return XbaseWithRichstringValueConverterService.class;
	}
	
	@Override
	public Class<? extends ITypeComputer> bindITypeComputer() {
		return XbaseWithRichstringTypeComputer.class;
	}
	
}
