/*
 * generated by Xtext
 */
package org.jnario.xbase.richstring;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XbaseWithRichstringStandaloneSetup extends XbaseWithRichstringStandaloneSetupGenerated{

	public static void doSetup() {
		new XbaseWithRichstringStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

