/*
 * generated by Xtext
 */
package org.jnario.spec.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.common.types.JvmFormalParameter;
import org.eclipse.xtext.common.types.JvmGenericArrayTypeReference;
import org.eclipse.xtext.common.types.JvmInnerTypeReference;
import org.eclipse.xtext.common.types.JvmLowerBound;
import org.eclipse.xtext.common.types.JvmParameterizedTypeReference;
import org.eclipse.xtext.common.types.JvmTypeParameter;
import org.eclipse.xtext.common.types.JvmUpperBound;
import org.eclipse.xtext.common.types.JvmWildcardTypeReference;
import org.eclipse.xtext.common.types.TypesPackage;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.eclipse.xtext.xbase.XAssignment;
import org.eclipse.xtext.xbase.XBasicForLoopExpression;
import org.eclipse.xtext.xbase.XBinaryOperation;
import org.eclipse.xtext.xbase.XBlockExpression;
import org.eclipse.xtext.xbase.XBooleanLiteral;
import org.eclipse.xtext.xbase.XCasePart;
import org.eclipse.xtext.xbase.XCastedExpression;
import org.eclipse.xtext.xbase.XCatchClause;
import org.eclipse.xtext.xbase.XClosure;
import org.eclipse.xtext.xbase.XConstructorCall;
import org.eclipse.xtext.xbase.XDoWhileExpression;
import org.eclipse.xtext.xbase.XFeatureCall;
import org.eclipse.xtext.xbase.XForLoopExpression;
import org.eclipse.xtext.xbase.XIfExpression;
import org.eclipse.xtext.xbase.XInstanceOfExpression;
import org.eclipse.xtext.xbase.XListLiteral;
import org.eclipse.xtext.xbase.XMemberFeatureCall;
import org.eclipse.xtext.xbase.XNullLiteral;
import org.eclipse.xtext.xbase.XNumberLiteral;
import org.eclipse.xtext.xbase.XPostfixOperation;
import org.eclipse.xtext.xbase.XReturnExpression;
import org.eclipse.xtext.xbase.XSetLiteral;
import org.eclipse.xtext.xbase.XStringLiteral;
import org.eclipse.xtext.xbase.XSwitchExpression;
import org.eclipse.xtext.xbase.XSynchronizedExpression;
import org.eclipse.xtext.xbase.XThrowExpression;
import org.eclipse.xtext.xbase.XTryCatchFinallyExpression;
import org.eclipse.xtext.xbase.XTypeLiteral;
import org.eclipse.xtext.xbase.XUnaryOperation;
import org.eclipse.xtext.xbase.XVariableDeclaration;
import org.eclipse.xtext.xbase.XWhileExpression;
import org.eclipse.xtext.xbase.XbasePackage;
import org.eclipse.xtext.xbase.annotations.serializer.XbaseWithAnnotationsSemanticSequencer;
import org.eclipse.xtext.xbase.annotations.xAnnotations.XAnnotation;
import org.eclipse.xtext.xbase.annotations.xAnnotations.XAnnotationElementValuePair;
import org.eclipse.xtext.xbase.annotations.xAnnotations.XAnnotationsPackage;
import org.eclipse.xtext.xtype.XFunctionTypeRef;
import org.eclipse.xtext.xtype.XImportDeclaration;
import org.eclipse.xtext.xtype.XImportSection;
import org.eclipse.xtext.xtype.XtypePackage;
import org.jnario.Assertion;
import org.jnario.ExampleCell;
import org.jnario.ExampleColumn;
import org.jnario.ExampleRow;
import org.jnario.ExampleTable;
import org.jnario.JnarioField;
import org.jnario.JnarioFunction;
import org.jnario.JnarioMember;
import org.jnario.JnarioPackage;
import org.jnario.JnarioParameter;
import org.jnario.JnarioTypeDeclaration;
import org.jnario.Should;
import org.jnario.ShouldThrow;
import org.jnario.spec.services.SpecGrammarAccess;
import org.jnario.spec.spec.After;
import org.jnario.spec.spec.Before;
import org.jnario.spec.spec.Example;
import org.jnario.spec.spec.ExampleGroup;
import org.jnario.spec.spec.SpecFile;
import org.jnario.spec.spec.SpecPackage;

@SuppressWarnings("all")
public class SpecSemanticSequencer extends XbaseWithAnnotationsSemanticSequencer {

	@Inject
	private SpecGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == JnarioPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case JnarioPackage.ASSERTION:
				sequence_Assertion(context, (Assertion) semanticObject); 
				return; 
			case JnarioPackage.EXAMPLE_CELL:
				sequence_ExampleCell(context, (ExampleCell) semanticObject); 
				return; 
			case JnarioPackage.EXAMPLE_COLUMN:
				sequence_ExampleColumn(context, (ExampleColumn) semanticObject); 
				return; 
			case JnarioPackage.EXAMPLE_ROW:
				sequence_ExampleRow(context, (ExampleRow) semanticObject); 
				return; 
			case JnarioPackage.EXAMPLE_TABLE:
				sequence_Member(context, (ExampleTable) semanticObject); 
				return; 
			case JnarioPackage.JNARIO_FIELD:
				sequence_Member(context, (JnarioField) semanticObject); 
				return; 
			case JnarioPackage.JNARIO_FUNCTION:
				sequence_Member(context, (JnarioFunction) semanticObject); 
				return; 
			case JnarioPackage.JNARIO_MEMBER:
				sequence_Member_After_2_3_0_Before_2_2_0_ExampleGroup_2_1_0_ExampleGroup_2_4_0_ExampleTable_2_5_0_Example_2_0_0_JnarioField_2_6_0_JnarioFunction_2_7_0(context, (JnarioMember) semanticObject); 
				return; 
			case JnarioPackage.JNARIO_PARAMETER:
				sequence_Parameter(context, (JnarioParameter) semanticObject); 
				return; 
			case JnarioPackage.JNARIO_TYPE_DECLARATION:
				sequence_Type_ExampleGroup_2_0(context, (JnarioTypeDeclaration) semanticObject); 
				return; 
			case JnarioPackage.SHOULD:
				sequence_XRelationalExpression(context, (Should) semanticObject); 
				return; 
			case JnarioPackage.SHOULD_THROW:
				sequence_XRelationalExpression(context, (ShouldThrow) semanticObject); 
				return; 
			}
		else if (epackage == SpecPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SpecPackage.AFTER:
				sequence_Member(context, (After) semanticObject); 
				return; 
			case SpecPackage.BEFORE:
				sequence_Member(context, (Before) semanticObject); 
				return; 
			case SpecPackage.EXAMPLE:
				sequence_Member(context, (Example) semanticObject); 
				return; 
			case SpecPackage.EXAMPLE_GROUP:
				if (rule == grammarAccess.getMemberRule()) {
					sequence_Member(context, (ExampleGroup) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getTypeRule()) {
					sequence_Type(context, (ExampleGroup) semanticObject); 
					return; 
				}
				else break;
			case SpecPackage.SPEC_FILE:
				sequence_SpecFile(context, (SpecFile) semanticObject); 
				return; 
			}
		else if (epackage == TypesPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TypesPackage.JVM_FORMAL_PARAMETER:
				if (rule == grammarAccess.getFullJvmFormalParameterRule()) {
					sequence_FullJvmFormalParameter(context, (JvmFormalParameter) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getJvmFormalParameterRule()) {
					sequence_JvmFormalParameter(context, (JvmFormalParameter) semanticObject); 
					return; 
				}
				else break;
			case TypesPackage.JVM_GENERIC_ARRAY_TYPE_REFERENCE:
				sequence_JvmTypeReference(context, (JvmGenericArrayTypeReference) semanticObject); 
				return; 
			case TypesPackage.JVM_INNER_TYPE_REFERENCE:
				sequence_JvmParameterizedTypeReference(context, (JvmInnerTypeReference) semanticObject); 
				return; 
			case TypesPackage.JVM_LOWER_BOUND:
				if (rule == grammarAccess.getJvmLowerBoundAndedRule()) {
					sequence_JvmLowerBoundAnded(context, (JvmLowerBound) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getJvmLowerBoundRule()) {
					sequence_JvmLowerBound(context, (JvmLowerBound) semanticObject); 
					return; 
				}
				else break;
			case TypesPackage.JVM_PARAMETERIZED_TYPE_REFERENCE:
				if (action == grammarAccess.getJvmParameterizedTypeReferenceAccess().getJvmInnerTypeReferenceOuterAction_1_4_0_0_0()) {
					sequence_JvmParameterizedTypeReference_JvmInnerTypeReference_1_4_0_0_0(context, (JvmParameterizedTypeReference) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getJvmTypeReferenceRule()
						|| action == grammarAccess.getJvmTypeReferenceAccess().getJvmGenericArrayTypeReferenceComponentTypeAction_0_1_0_0()
						|| rule == grammarAccess.getJvmParameterizedTypeReferenceRule()
						|| rule == grammarAccess.getJvmArgumentTypeReferenceRule()) {
					sequence_JvmParameterizedTypeReference(context, (JvmParameterizedTypeReference) semanticObject); 
					return; 
				}
				else break;
			case TypesPackage.JVM_TYPE_PARAMETER:
				sequence_JvmTypeParameter(context, (JvmTypeParameter) semanticObject); 
				return; 
			case TypesPackage.JVM_UPPER_BOUND:
				if (rule == grammarAccess.getJvmUpperBoundAndedRule()) {
					sequence_JvmUpperBoundAnded(context, (JvmUpperBound) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getJvmUpperBoundRule()) {
					sequence_JvmUpperBound(context, (JvmUpperBound) semanticObject); 
					return; 
				}
				else break;
			case TypesPackage.JVM_WILDCARD_TYPE_REFERENCE:
				sequence_JvmWildcardTypeReference(context, (JvmWildcardTypeReference) semanticObject); 
				return; 
			}
		else if (epackage == XAnnotationsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XAnnotationsPackage.XANNOTATION:
				sequence_XAnnotation(context, (XAnnotation) semanticObject); 
				return; 
			case XAnnotationsPackage.XANNOTATION_ELEMENT_VALUE_PAIR:
				sequence_XAnnotationElementValuePair(context, (XAnnotationElementValuePair) semanticObject); 
				return; 
			}
		else if (epackage == XbasePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XbasePackage.XASSIGNMENT:
				sequence_XAssignment_XMemberFeatureCall(context, (XAssignment) semanticObject); 
				return; 
			case XbasePackage.XBASIC_FOR_LOOP_EXPRESSION:
				sequence_XBasicForLoopExpression(context, (XBasicForLoopExpression) semanticObject); 
				return; 
			case XbasePackage.XBINARY_OPERATION:
				sequence_XAdditiveExpression_XAndExpression_XAssignment_XEqualityExpression_XMultiplicativeExpression_XOrExpression_XOtherOperatorExpression_XRelationalExpression(context, (XBinaryOperation) semanticObject); 
				return; 
			case XbasePackage.XBLOCK_EXPRESSION:
				if (rule == grammarAccess.getXPrimaryExpressionRule()
						|| rule == grammarAccess.getXRelationalExpressionRule()
						|| action == grammarAccess.getXRelationalExpressionAccess().getShouldLeftOperandAction_1_0_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getShouldThrowExpressionAction_1_1_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getXInstanceOfExpressionExpressionAction_1_2_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getXBinaryOperationLeftOperandAction_1_3_0_0_0()
						|| rule == grammarAccess.getXAnnotationElementValueOrCommaListRule()
						|| action == grammarAccess.getXAnnotationElementValueOrCommaListAccess().getXListLiteralElementsAction_1_1_0()
						|| rule == grammarAccess.getXAnnotationElementValueRule()
						|| rule == grammarAccess.getXAnnotationOrExpressionRule()
						|| rule == grammarAccess.getXExpressionRule()
						|| rule == grammarAccess.getXAssignmentRule()
						|| action == grammarAccess.getXAssignmentAccess().getXBinaryOperationLeftOperandAction_1_1_0_0_0()
						|| rule == grammarAccess.getXOrExpressionRule()
						|| action == grammarAccess.getXOrExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXAndExpressionRule()
						|| action == grammarAccess.getXAndExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXEqualityExpressionRule()
						|| action == grammarAccess.getXEqualityExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXOtherOperatorExpressionRule()
						|| action == grammarAccess.getXOtherOperatorExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXAdditiveExpressionRule()
						|| action == grammarAccess.getXAdditiveExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXMultiplicativeExpressionRule()
						|| action == grammarAccess.getXMultiplicativeExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXUnaryOperationRule()
						|| rule == grammarAccess.getXCastedExpressionRule()
						|| action == grammarAccess.getXCastedExpressionAccess().getXCastedExpressionTargetAction_1_0_0_0()
						|| rule == grammarAccess.getXPostfixOperationRule()
						|| action == grammarAccess.getXPostfixOperationAccess().getXPostfixOperationOperandAction_1_0_0()
						|| rule == grammarAccess.getXMemberFeatureCallRule()
						|| action == grammarAccess.getXMemberFeatureCallAccess().getXAssignmentAssignableAction_1_0_0_0_0()
						|| action == grammarAccess.getXMemberFeatureCallAccess().getXMemberFeatureCallMemberCallTargetAction_1_1_0_0_0()
						|| rule == grammarAccess.getXParenthesizedExpressionRule()
						|| rule == grammarAccess.getXBlockExpressionRule()
						|| rule == grammarAccess.getXExpressionOrVarDeclarationRule()) {
					sequence_XBlockExpression(context, (XBlockExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getXExpressionInClosureRule()) {
					sequence_XExpressionInClosure(context, (XBlockExpression) semanticObject); 
					return; 
				}
				else break;
			case XbasePackage.XBOOLEAN_LITERAL:
				sequence_XBooleanLiteral(context, (XBooleanLiteral) semanticObject); 
				return; 
			case XbasePackage.XCASE_PART:
				sequence_XCasePart(context, (XCasePart) semanticObject); 
				return; 
			case XbasePackage.XCASTED_EXPRESSION:
				sequence_XCastedExpression(context, (XCastedExpression) semanticObject); 
				return; 
			case XbasePackage.XCATCH_CLAUSE:
				sequence_XCatchClause(context, (XCatchClause) semanticObject); 
				return; 
			case XbasePackage.XCLOSURE:
				if (rule == grammarAccess.getXPrimaryExpressionRule()
						|| rule == grammarAccess.getXRelationalExpressionRule()
						|| action == grammarAccess.getXRelationalExpressionAccess().getShouldLeftOperandAction_1_0_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getShouldThrowExpressionAction_1_1_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getXInstanceOfExpressionExpressionAction_1_2_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getXBinaryOperationLeftOperandAction_1_3_0_0_0()
						|| rule == grammarAccess.getXAnnotationElementValueOrCommaListRule()
						|| action == grammarAccess.getXAnnotationElementValueOrCommaListAccess().getXListLiteralElementsAction_1_1_0()
						|| rule == grammarAccess.getXAnnotationElementValueRule()
						|| rule == grammarAccess.getXAnnotationOrExpressionRule()
						|| rule == grammarAccess.getXExpressionRule()
						|| rule == grammarAccess.getXAssignmentRule()
						|| action == grammarAccess.getXAssignmentAccess().getXBinaryOperationLeftOperandAction_1_1_0_0_0()
						|| rule == grammarAccess.getXOrExpressionRule()
						|| action == grammarAccess.getXOrExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXAndExpressionRule()
						|| action == grammarAccess.getXAndExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXEqualityExpressionRule()
						|| action == grammarAccess.getXEqualityExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXOtherOperatorExpressionRule()
						|| action == grammarAccess.getXOtherOperatorExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXAdditiveExpressionRule()
						|| action == grammarAccess.getXAdditiveExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXMultiplicativeExpressionRule()
						|| action == grammarAccess.getXMultiplicativeExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXUnaryOperationRule()
						|| rule == grammarAccess.getXCastedExpressionRule()
						|| action == grammarAccess.getXCastedExpressionAccess().getXCastedExpressionTargetAction_1_0_0_0()
						|| rule == grammarAccess.getXPostfixOperationRule()
						|| action == grammarAccess.getXPostfixOperationAccess().getXPostfixOperationOperandAction_1_0_0()
						|| rule == grammarAccess.getXMemberFeatureCallRule()
						|| action == grammarAccess.getXMemberFeatureCallAccess().getXAssignmentAssignableAction_1_0_0_0_0()
						|| action == grammarAccess.getXMemberFeatureCallAccess().getXMemberFeatureCallMemberCallTargetAction_1_1_0_0_0()
						|| rule == grammarAccess.getXLiteralRule()
						|| rule == grammarAccess.getXClosureRule()
						|| rule == grammarAccess.getXParenthesizedExpressionRule()
						|| rule == grammarAccess.getXExpressionOrVarDeclarationRule()) {
					sequence_XClosure(context, (XClosure) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getXShortClosureRule()) {
					sequence_XShortClosure(context, (XClosure) semanticObject); 
					return; 
				}
				else break;
			case XbasePackage.XCONSTRUCTOR_CALL:
				sequence_XConstructorCall(context, (XConstructorCall) semanticObject); 
				return; 
			case XbasePackage.XDO_WHILE_EXPRESSION:
				sequence_XDoWhileExpression(context, (XDoWhileExpression) semanticObject); 
				return; 
			case XbasePackage.XFEATURE_CALL:
				sequence_XFeatureCall(context, (XFeatureCall) semanticObject); 
				return; 
			case XbasePackage.XFOR_LOOP_EXPRESSION:
				sequence_XForLoopExpression(context, (XForLoopExpression) semanticObject); 
				return; 
			case XbasePackage.XIF_EXPRESSION:
				sequence_XIfExpression(context, (XIfExpression) semanticObject); 
				return; 
			case XbasePackage.XINSTANCE_OF_EXPRESSION:
				sequence_XRelationalExpression(context, (XInstanceOfExpression) semanticObject); 
				return; 
			case XbasePackage.XLIST_LITERAL:
				if (rule == grammarAccess.getXAnnotationElementValueOrCommaListRule()) {
					sequence_XAnnotationElementValueOrCommaList_XListLiteral(context, (XListLiteral) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getXAnnotationElementValueRule()) {
					sequence_XAnnotationElementValue_XListLiteral(context, (XListLiteral) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getXPrimaryExpressionRule()
						|| rule == grammarAccess.getXRelationalExpressionRule()
						|| action == grammarAccess.getXRelationalExpressionAccess().getShouldLeftOperandAction_1_0_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getShouldThrowExpressionAction_1_1_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getXInstanceOfExpressionExpressionAction_1_2_0_0_0()
						|| action == grammarAccess.getXRelationalExpressionAccess().getXBinaryOperationLeftOperandAction_1_3_0_0_0()
						|| action == grammarAccess.getXAnnotationElementValueOrCommaListAccess().getXListLiteralElementsAction_1_1_0()
						|| rule == grammarAccess.getXAnnotationOrExpressionRule()
						|| rule == grammarAccess.getXExpressionRule()
						|| rule == grammarAccess.getXAssignmentRule()
						|| action == grammarAccess.getXAssignmentAccess().getXBinaryOperationLeftOperandAction_1_1_0_0_0()
						|| rule == grammarAccess.getXOrExpressionRule()
						|| action == grammarAccess.getXOrExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXAndExpressionRule()
						|| action == grammarAccess.getXAndExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXEqualityExpressionRule()
						|| action == grammarAccess.getXEqualityExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXOtherOperatorExpressionRule()
						|| action == grammarAccess.getXOtherOperatorExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXAdditiveExpressionRule()
						|| action == grammarAccess.getXAdditiveExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXMultiplicativeExpressionRule()
						|| action == grammarAccess.getXMultiplicativeExpressionAccess().getXBinaryOperationLeftOperandAction_1_0_0_0()
						|| rule == grammarAccess.getXUnaryOperationRule()
						|| rule == grammarAccess.getXCastedExpressionRule()
						|| action == grammarAccess.getXCastedExpressionAccess().getXCastedExpressionTargetAction_1_0_0_0()
						|| rule == grammarAccess.getXPostfixOperationRule()
						|| action == grammarAccess.getXPostfixOperationAccess().getXPostfixOperationOperandAction_1_0_0()
						|| rule == grammarAccess.getXMemberFeatureCallRule()
						|| action == grammarAccess.getXMemberFeatureCallAccess().getXAssignmentAssignableAction_1_0_0_0_0()
						|| action == grammarAccess.getXMemberFeatureCallAccess().getXMemberFeatureCallMemberCallTargetAction_1_1_0_0_0()
						|| rule == grammarAccess.getXLiteralRule()
						|| rule == grammarAccess.getXCollectionLiteralRule()
						|| rule == grammarAccess.getXListLiteralRule()
						|| rule == grammarAccess.getXParenthesizedExpressionRule()
						|| rule == grammarAccess.getXExpressionOrVarDeclarationRule()) {
					sequence_XListLiteral(context, (XListLiteral) semanticObject); 
					return; 
				}
				else break;
			case XbasePackage.XMEMBER_FEATURE_CALL:
				sequence_XMemberFeatureCall(context, (XMemberFeatureCall) semanticObject); 
				return; 
			case XbasePackage.XNULL_LITERAL:
				sequence_XNullLiteral(context, (XNullLiteral) semanticObject); 
				return; 
			case XbasePackage.XNUMBER_LITERAL:
				sequence_XNumberLiteral(context, (XNumberLiteral) semanticObject); 
				return; 
			case XbasePackage.XPOSTFIX_OPERATION:
				sequence_XPostfixOperation(context, (XPostfixOperation) semanticObject); 
				return; 
			case XbasePackage.XRETURN_EXPRESSION:
				sequence_XReturnExpression(context, (XReturnExpression) semanticObject); 
				return; 
			case XbasePackage.XSET_LITERAL:
				sequence_XSetLiteral(context, (XSetLiteral) semanticObject); 
				return; 
			case XbasePackage.XSTRING_LITERAL:
				sequence_XStringLiteral(context, (XStringLiteral) semanticObject); 
				return; 
			case XbasePackage.XSWITCH_EXPRESSION:
				sequence_XSwitchExpression(context, (XSwitchExpression) semanticObject); 
				return; 
			case XbasePackage.XSYNCHRONIZED_EXPRESSION:
				sequence_XSynchronizedExpression(context, (XSynchronizedExpression) semanticObject); 
				return; 
			case XbasePackage.XTHROW_EXPRESSION:
				sequence_XThrowExpression(context, (XThrowExpression) semanticObject); 
				return; 
			case XbasePackage.XTRY_CATCH_FINALLY_EXPRESSION:
				sequence_XTryCatchFinallyExpression(context, (XTryCatchFinallyExpression) semanticObject); 
				return; 
			case XbasePackage.XTYPE_LITERAL:
				sequence_XTypeLiteral(context, (XTypeLiteral) semanticObject); 
				return; 
			case XbasePackage.XUNARY_OPERATION:
				sequence_XUnaryOperation(context, (XUnaryOperation) semanticObject); 
				return; 
			case XbasePackage.XVARIABLE_DECLARATION:
				sequence_XVariableDeclaration(context, (XVariableDeclaration) semanticObject); 
				return; 
			case XbasePackage.XWHILE_EXPRESSION:
				sequence_XWhileExpression(context, (XWhileExpression) semanticObject); 
				return; 
			}
		else if (epackage == XtypePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XtypePackage.XFUNCTION_TYPE_REF:
				sequence_XFunctionTypeRef(context, (XFunctionTypeRef) semanticObject); 
				return; 
			case XtypePackage.XIMPORT_DECLARATION:
				sequence_XImportDeclaration(context, (XImportDeclaration) semanticObject); 
				return; 
			case XtypePackage.XIMPORT_SECTION:
				sequence_XImportSection(context, (XImportSection) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     XPrimaryExpression returns Assertion
	 *     XRelationalExpression returns Assertion
	 *     XRelationalExpression.Should_1_0_0_0_0 returns Assertion
	 *     XRelationalExpression.ShouldThrow_1_1_0_0_0 returns Assertion
	 *     XRelationalExpression.XInstanceOfExpression_1_2_0_0_0 returns Assertion
	 *     XRelationalExpression.XBinaryOperation_1_3_0_0_0 returns Assertion
	 *     Assertion returns Assertion
	 *     XAnnotationElementValueOrCommaList returns Assertion
	 *     XAnnotationElementValueOrCommaList.XListLiteral_1_1_0 returns Assertion
	 *     XAnnotationElementValue returns Assertion
	 *     XAnnotationOrExpression returns Assertion
	 *     XExpression returns Assertion
	 *     XAssignment returns Assertion
	 *     XAssignment.XBinaryOperation_1_1_0_0_0 returns Assertion
	 *     XOrExpression returns Assertion
	 *     XOrExpression.XBinaryOperation_1_0_0_0 returns Assertion
	 *     XAndExpression returns Assertion
	 *     XAndExpression.XBinaryOperation_1_0_0_0 returns Assertion
	 *     XEqualityExpression returns Assertion
	 *     XEqualityExpression.XBinaryOperation_1_0_0_0 returns Assertion
	 *     XOtherOperatorExpression returns Assertion
	 *     XOtherOperatorExpression.XBinaryOperation_1_0_0_0 returns Assertion
	 *     XAdditiveExpression returns Assertion
	 *     XAdditiveExpression.XBinaryOperation_1_0_0_0 returns Assertion
	 *     XMultiplicativeExpression returns Assertion
	 *     XMultiplicativeExpression.XBinaryOperation_1_0_0_0 returns Assertion
	 *     XUnaryOperation returns Assertion
	 *     XCastedExpression returns Assertion
	 *     XCastedExpression.XCastedExpression_1_0_0_0 returns Assertion
	 *     XPostfixOperation returns Assertion
	 *     XPostfixOperation.XPostfixOperation_1_0_0 returns Assertion
	 *     XMemberFeatureCall returns Assertion
	 *     XMemberFeatureCall.XAssignment_1_0_0_0_0 returns Assertion
	 *     XMemberFeatureCall.XMemberFeatureCall_1_1_0_0_0 returns Assertion
	 *     XParenthesizedExpression returns Assertion
	 *     XExpressionOrVarDeclaration returns Assertion
	 *
	 * Constraint:
	 *     expression=XExpression
	 */
	protected void sequence_Assertion(ISerializationContext context, Assertion semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JnarioPackage.Literals.ASSERTION__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JnarioPackage.Literals.ASSERTION__EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAssertionAccess().getExpressionXExpressionParserRuleCall_2_0(), semanticObject.getExpression());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ExampleCell returns ExampleCell
	 *
	 * Constraint:
	 *     expression=XExpression
	 */
	protected void sequence_ExampleCell(ISerializationContext context, ExampleCell semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JnarioPackage.Literals.JNARIO_FUNCTION__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JnarioPackage.Literals.JNARIO_FUNCTION__EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExampleCellAccess().getExpressionXExpressionParserRuleCall_0(), semanticObject.getExpression());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ExampleColumn returns ExampleColumn
	 *
	 * Constraint:
	 *     (type=JvmTypeReference? name=ValidID)
	 */
	protected void sequence_ExampleColumn(ISerializationContext context, ExampleColumn semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ExampleRow returns ExampleRow
	 *
	 * Constraint:
	 *     cells+=ExampleCell*
	 */
	protected void sequence_ExampleRow(ISerializationContext context, ExampleRow semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns After
	 *
	 * Constraint:
	 *     (annotationInfo=Member_After_2_3_0 modifiers+='all'? name=STRING? expression=XExpression)
	 */
	protected void sequence_Member(ISerializationContext context, After semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member.Example_2_0_0 returns JnarioMember
	 *     Member.ExampleGroup_2_1_0 returns JnarioMember
	 *     Member.Before_2_2_0 returns JnarioMember
	 *     Member.After_2_3_0 returns JnarioMember
	 *     Member.ExampleGroup_2_4_0 returns JnarioMember
	 *     Member.ExampleTable_2_5_0 returns JnarioMember
	 *     Member.JnarioField_2_6_0 returns JnarioMember
	 *     Member.JnarioFunction_2_7_0 returns JnarioMember
	 *
	 * Constraint:
	 *     annotations+=XAnnotation*
	 */
	protected void sequence_Member_After_2_3_0_Before_2_2_0_ExampleGroup_2_1_0_ExampleGroup_2_4_0_ExampleTable_2_5_0_Example_2_0_0_JnarioField_2_6_0_JnarioFunction_2_7_0(ISerializationContext context, JnarioMember semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns Before
	 *
	 * Constraint:
	 *     (annotationInfo=Member_Before_2_2_0 modifiers+='all'? name=STRING? expression=XExpression)
	 */
	protected void sequence_Member(ISerializationContext context, Before semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns Example
	 *
	 * Constraint:
	 *     (annotationInfo=Member_Example_2_0_0 pending?='pending'? expr=XExpression expression=XBlockExpression?)
	 */
	protected void sequence_Member(ISerializationContext context, Example semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns ExampleGroup
	 *
	 * Constraint:
	 *     (
	 *         (annotationInfo=Member_ExampleGroup_2_1_0 preamble='describe' targetType=JvmTypeReference? name=STRING? members+=Member*) | 
	 *         (annotationInfo=Member_ExampleGroup_2_4_0 preamble='context' targetOperation=[JvmOperation|Method]? name=STRING? members+=Member*)
	 *     )
	 */
	protected void sequence_Member(ISerializationContext context, ExampleGroup semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns ExampleTable
	 *
	 * Constraint:
	 *     (annotationInfo=Member_ExampleTable_2_5_0 name=ID? columns+=ExampleColumn* rows+=ExampleRow*)
	 */
	protected void sequence_Member(ISerializationContext context, ExampleTable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns JnarioField
	 *
	 * Constraint:
	 *     (
	 *         annotationInfo=Member_JnarioField_2_6_0 
	 *         modifiers+=CommonModifier* 
	 *         (
	 *             (modifiers+=FieldModifier modifiers+=CommonModifier* type=JvmTypeReference? name=ValidID) | 
	 *             (modifiers+='extension' (modifiers+=FieldModifier | modifiers+=CommonModifier)* type=JvmTypeReference name=ValidID?) | 
	 *             (
	 *                 modifiers+=FieldModifier 
	 *                 modifiers+=CommonModifier* 
	 *                 modifiers+='extension' 
	 *                 modifiers+=CommonModifier* 
	 *                 type=JvmTypeReference 
	 *                 name=ValidID?
	 *             ) | 
	 *             (type=JvmTypeReference name=ValidID)
	 *         ) 
	 *         initialValue=XExpression?
	 *     )
	 */
	protected void sequence_Member(ISerializationContext context, JnarioField semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns JnarioFunction
	 *
	 * Constraint:
	 *     (
	 *         annotationInfo=Member_JnarioFunction_2_7_0 
	 *         modifiers+=CommonModifier* 
	 *         modifiers+=MethodModifier 
	 *         (modifiers+=CommonModifier | modifiers+=MethodModifier)* 
	 *         (typeParameters+=JvmTypeParameter typeParameters+=JvmTypeParameter*)? 
	 *         ((returnType=JvmTypeReference name=ValidID) | name=ValidID) 
	 *         (parameters+=Parameter parameters+=Parameter*)? 
	 *         (exceptions+=JvmTypeReference exceptions+=JvmTypeReference*)? 
	 *         expression=XBlockExpression?
	 *     )
	 */
	protected void sequence_Member(ISerializationContext context, JnarioFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Parameter returns JnarioParameter
	 *
	 * Constraint:
	 *     (annotations+=XAnnotation* (extension?='extension' annotations+=XAnnotation*)? parameterType=JvmTypeReference varArg?='...'? name=ValidID)
	 */
	protected void sequence_Parameter(ISerializationContext context, JnarioParameter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SpecFile returns SpecFile
	 *
	 * Constraint:
	 *     (package=QualifiedName? importSection=XImportSection? xtendTypes+=Type*)
	 */
	protected void sequence_SpecFile(ISerializationContext context, SpecFile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns ExampleGroup
	 *
	 * Constraint:
	 *     (annotationInfo=Type_ExampleGroup_2_0 preamble='describe' targetType=JvmTypeReference? name=STRING? members+=Member*)
	 */
	protected void sequence_Type(ISerializationContext context, ExampleGroup semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type.ExampleGroup_2_0 returns JnarioTypeDeclaration
	 *
	 * Constraint:
	 *     annotations+=XAnnotation*
	 */
	protected void sequence_Type_ExampleGroup_2_0(ISerializationContext context, JnarioTypeDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XPrimaryExpression returns XBinaryOperation
	 *     XRelationalExpression returns XBinaryOperation
	 *     XRelationalExpression.Should_1_0_0_0_0 returns XBinaryOperation
	 *     XRelationalExpression.ShouldThrow_1_1_0_0_0 returns XBinaryOperation
	 *     XRelationalExpression.XInstanceOfExpression_1_2_0_0_0 returns XBinaryOperation
	 *     XRelationalExpression.XBinaryOperation_1_3_0_0_0 returns XBinaryOperation
	 *     XAnnotationElementValueOrCommaList returns XBinaryOperation
	 *     XAnnotationElementValueOrCommaList.XListLiteral_1_1_0 returns XBinaryOperation
	 *     XAnnotationElementValue returns XBinaryOperation
	 *     XAnnotationOrExpression returns XBinaryOperation
	 *     XExpression returns XBinaryOperation
	 *     XAssignment returns XBinaryOperation
	 *     XAssignment.XBinaryOperation_1_1_0_0_0 returns XBinaryOperation
	 *     XOrExpression returns XBinaryOperation
	 *     XOrExpression.XBinaryOperation_1_0_0_0 returns XBinaryOperation
	 *     XAndExpression returns XBinaryOperation
	 *     XAndExpression.XBinaryOperation_1_0_0_0 returns XBinaryOperation
	 *     XEqualityExpression returns XBinaryOperation
	 *     XEqualityExpression.XBinaryOperation_1_0_0_0 returns XBinaryOperation
	 *     XOtherOperatorExpression returns XBinaryOperation
	 *     XOtherOperatorExpression.XBinaryOperation_1_0_0_0 returns XBinaryOperation
	 *     XAdditiveExpression returns XBinaryOperation
	 *     XAdditiveExpression.XBinaryOperation_1_0_0_0 returns XBinaryOperation
	 *     XMultiplicativeExpression returns XBinaryOperation
	 *     XMultiplicativeExpression.XBinaryOperation_1_0_0_0 returns XBinaryOperation
	 *     XUnaryOperation returns XBinaryOperation
	 *     XCastedExpression returns XBinaryOperation
	 *     XCastedExpression.XCastedExpression_1_0_0_0 returns XBinaryOperation
	 *     XPostfixOperation returns XBinaryOperation
	 *     XPostfixOperation.XPostfixOperation_1_0_0 returns XBinaryOperation
	 *     XMemberFeatureCall returns XBinaryOperation
	 *     XMemberFeatureCall.XAssignment_1_0_0_0_0 returns XBinaryOperation
	 *     XMemberFeatureCall.XMemberFeatureCall_1_1_0_0_0 returns XBinaryOperation
	 *     XParenthesizedExpression returns XBinaryOperation
	 *     XExpressionOrVarDeclaration returns XBinaryOperation
	 *
	 * Constraint:
	 *     (
	 *         (leftOperand=XRelationalExpression_XBinaryOperation_1_3_0_0_0 feature=[JvmIdentifiableElement|OpCompare] rightOperand=XOtherOperatorExpression) | 
	 *         (leftOperand=XAssignment_XBinaryOperation_1_1_0_0_0 feature=[JvmIdentifiableElement|OpMultiAssign] rightOperand=XAssignment) | 
	 *         (leftOperand=XOrExpression_XBinaryOperation_1_0_0_0 feature=[JvmIdentifiableElement|OpOr] rightOperand=XAndExpression) | 
	 *         (leftOperand=XAndExpression_XBinaryOperation_1_0_0_0 feature=[JvmIdentifiableElement|OpAnd] rightOperand=XEqualityExpression) | 
	 *         (leftOperand=XEqualityExpression_XBinaryOperation_1_0_0_0 feature=[JvmIdentifiableElement|OpEquality] rightOperand=XRelationalExpression) | 
	 *         (leftOperand=XOtherOperatorExpression_XBinaryOperation_1_0_0_0 feature=[JvmIdentifiableElement|OpOther] rightOperand=XAdditiveExpression) | 
	 *         (leftOperand=XAdditiveExpression_XBinaryOperation_1_0_0_0 feature=[JvmIdentifiableElement|OpAdd] rightOperand=XMultiplicativeExpression) | 
	 *         (leftOperand=XMultiplicativeExpression_XBinaryOperation_1_0_0_0 feature=[JvmIdentifiableElement|OpMulti] rightOperand=XUnaryOperation)
	 *     )
	 */
	protected void sequence_XAdditiveExpression_XAndExpression_XAssignment_XEqualityExpression_XMultiplicativeExpression_XOrExpression_XOtherOperatorExpression_XRelationalExpression(ISerializationContext context, XBinaryOperation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XPrimaryExpression returns Should
	 *     XRelationalExpression returns Should
	 *     XRelationalExpression.Should_1_0_0_0_0 returns Should
	 *     XRelationalExpression.ShouldThrow_1_1_0_0_0 returns Should
	 *     XRelationalExpression.XInstanceOfExpression_1_2_0_0_0 returns Should
	 *     XRelationalExpression.XBinaryOperation_1_3_0_0_0 returns Should
	 *     XAnnotationElementValueOrCommaList returns Should
	 *     XAnnotationElementValueOrCommaList.XListLiteral_1_1_0 returns Should
	 *     XAnnotationElementValue returns Should
	 *     XAnnotationOrExpression returns Should
	 *     XExpression returns Should
	 *     XAssignment returns Should
	 *     XAssignment.XBinaryOperation_1_1_0_0_0 returns Should
	 *     XOrExpression returns Should
	 *     XOrExpression.XBinaryOperation_1_0_0_0 returns Should
	 *     XAndExpression returns Should
	 *     XAndExpression.XBinaryOperation_1_0_0_0 returns Should
	 *     XEqualityExpression returns Should
	 *     XEqualityExpression.XBinaryOperation_1_0_0_0 returns Should
	 *     XOtherOperatorExpression returns Should
	 *     XOtherOperatorExpression.XBinaryOperation_1_0_0_0 returns Should
	 *     XAdditiveExpression returns Should
	 *     XAdditiveExpression.XBinaryOperation_1_0_0_0 returns Should
	 *     XMultiplicativeExpression returns Should
	 *     XMultiplicativeExpression.XBinaryOperation_1_0_0_0 returns Should
	 *     XUnaryOperation returns Should
	 *     XCastedExpression returns Should
	 *     XCastedExpression.XCastedExpression_1_0_0_0 returns Should
	 *     XPostfixOperation returns Should
	 *     XPostfixOperation.XPostfixOperation_1_0_0 returns Should
	 *     XMemberFeatureCall returns Should
	 *     XMemberFeatureCall.XAssignment_1_0_0_0_0 returns Should
	 *     XMemberFeatureCall.XMemberFeatureCall_1_1_0_0_0 returns Should
	 *     XParenthesizedExpression returns Should
	 *     XExpressionOrVarDeclaration returns Should
	 *
	 * Constraint:
	 *     (leftOperand=XRelationalExpression_Should_1_0_0_0_0 feature=[JvmIdentifiableElement|Should] rightOperand=XOtherOperatorExpression?)
	 */
	protected void sequence_XRelationalExpression(ISerializationContext context, Should semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XPrimaryExpression returns ShouldThrow
	 *     XRelationalExpression returns ShouldThrow
	 *     XRelationalExpression.Should_1_0_0_0_0 returns ShouldThrow
	 *     XRelationalExpression.ShouldThrow_1_1_0_0_0 returns ShouldThrow
	 *     XRelationalExpression.XInstanceOfExpression_1_2_0_0_0 returns ShouldThrow
	 *     XRelationalExpression.XBinaryOperation_1_3_0_0_0 returns ShouldThrow
	 *     XAnnotationElementValueOrCommaList returns ShouldThrow
	 *     XAnnotationElementValueOrCommaList.XListLiteral_1_1_0 returns ShouldThrow
	 *     XAnnotationElementValue returns ShouldThrow
	 *     XAnnotationOrExpression returns ShouldThrow
	 *     XExpression returns ShouldThrow
	 *     XAssignment returns ShouldThrow
	 *     XAssignment.XBinaryOperation_1_1_0_0_0 returns ShouldThrow
	 *     XOrExpression returns ShouldThrow
	 *     XOrExpression.XBinaryOperation_1_0_0_0 returns ShouldThrow
	 *     XAndExpression returns ShouldThrow
	 *     XAndExpression.XBinaryOperation_1_0_0_0 returns ShouldThrow
	 *     XEqualityExpression returns ShouldThrow
	 *     XEqualityExpression.XBinaryOperation_1_0_0_0 returns ShouldThrow
	 *     XOtherOperatorExpression returns ShouldThrow
	 *     XOtherOperatorExpression.XBinaryOperation_1_0_0_0 returns ShouldThrow
	 *     XAdditiveExpression returns ShouldThrow
	 *     XAdditiveExpression.XBinaryOperation_1_0_0_0 returns ShouldThrow
	 *     XMultiplicativeExpression returns ShouldThrow
	 *     XMultiplicativeExpression.XBinaryOperation_1_0_0_0 returns ShouldThrow
	 *     XUnaryOperation returns ShouldThrow
	 *     XCastedExpression returns ShouldThrow
	 *     XCastedExpression.XCastedExpression_1_0_0_0 returns ShouldThrow
	 *     XPostfixOperation returns ShouldThrow
	 *     XPostfixOperation.XPostfixOperation_1_0_0 returns ShouldThrow
	 *     XMemberFeatureCall returns ShouldThrow
	 *     XMemberFeatureCall.XAssignment_1_0_0_0_0 returns ShouldThrow
	 *     XMemberFeatureCall.XMemberFeatureCall_1_1_0_0_0 returns ShouldThrow
	 *     XParenthesizedExpression returns ShouldThrow
	 *     XExpressionOrVarDeclaration returns ShouldThrow
	 *
	 * Constraint:
	 *     (expression=XRelationalExpression_ShouldThrow_1_1_0_0_0 type=JvmTypeReference)
	 */
	protected void sequence_XRelationalExpression(ISerializationContext context, ShouldThrow semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JnarioPackage.Literals.SHOULD_THROW__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JnarioPackage.Literals.SHOULD_THROW__EXPRESSION));
			if (transientValues.isValueTransient(semanticObject, JnarioPackage.Literals.SHOULD_THROW__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JnarioPackage.Literals.SHOULD_THROW__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXRelationalExpressionAccess().getShouldThrowExpressionAction_1_1_0_0_0(), semanticObject.getExpression());
		feeder.accept(grammarAccess.getXRelationalExpressionAccess().getTypeJvmTypeReferenceParserRuleCall_1_1_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XPrimaryExpression returns XInstanceOfExpression
	 *     XRelationalExpression returns XInstanceOfExpression
	 *     XRelationalExpression.Should_1_0_0_0_0 returns XInstanceOfExpression
	 *     XRelationalExpression.ShouldThrow_1_1_0_0_0 returns XInstanceOfExpression
	 *     XRelationalExpression.XInstanceOfExpression_1_2_0_0_0 returns XInstanceOfExpression
	 *     XRelationalExpression.XBinaryOperation_1_3_0_0_0 returns XInstanceOfExpression
	 *     XAnnotationElementValueOrCommaList returns XInstanceOfExpression
	 *     XAnnotationElementValueOrCommaList.XListLiteral_1_1_0 returns XInstanceOfExpression
	 *     XAnnotationElementValue returns XInstanceOfExpression
	 *     XAnnotationOrExpression returns XInstanceOfExpression
	 *     XExpression returns XInstanceOfExpression
	 *     XAssignment returns XInstanceOfExpression
	 *     XAssignment.XBinaryOperation_1_1_0_0_0 returns XInstanceOfExpression
	 *     XOrExpression returns XInstanceOfExpression
	 *     XOrExpression.XBinaryOperation_1_0_0_0 returns XInstanceOfExpression
	 *     XAndExpression returns XInstanceOfExpression
	 *     XAndExpression.XBinaryOperation_1_0_0_0 returns XInstanceOfExpression
	 *     XEqualityExpression returns XInstanceOfExpression
	 *     XEqualityExpression.XBinaryOperation_1_0_0_0 returns XInstanceOfExpression
	 *     XOtherOperatorExpression returns XInstanceOfExpression
	 *     XOtherOperatorExpression.XBinaryOperation_1_0_0_0 returns XInstanceOfExpression
	 *     XAdditiveExpression returns XInstanceOfExpression
	 *     XAdditiveExpression.XBinaryOperation_1_0_0_0 returns XInstanceOfExpression
	 *     XMultiplicativeExpression returns XInstanceOfExpression
	 *     XMultiplicativeExpression.XBinaryOperation_1_0_0_0 returns XInstanceOfExpression
	 *     XUnaryOperation returns XInstanceOfExpression
	 *     XCastedExpression returns XInstanceOfExpression
	 *     XCastedExpression.XCastedExpression_1_0_0_0 returns XInstanceOfExpression
	 *     XPostfixOperation returns XInstanceOfExpression
	 *     XPostfixOperation.XPostfixOperation_1_0_0 returns XInstanceOfExpression
	 *     XMemberFeatureCall returns XInstanceOfExpression
	 *     XMemberFeatureCall.XAssignment_1_0_0_0_0 returns XInstanceOfExpression
	 *     XMemberFeatureCall.XMemberFeatureCall_1_1_0_0_0 returns XInstanceOfExpression
	 *     XParenthesizedExpression returns XInstanceOfExpression
	 *     XExpressionOrVarDeclaration returns XInstanceOfExpression
	 *
	 * Constraint:
	 *     (expression=XRelationalExpression_XInstanceOfExpression_1_2_0_0_0 type=JvmTypeReference)
	 */
	protected void sequence_XRelationalExpression(ISerializationContext context, XInstanceOfExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XbasePackage.Literals.XINSTANCE_OF_EXPRESSION__EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XbasePackage.Literals.XINSTANCE_OF_EXPRESSION__EXPRESSION));
			if (transientValues.isValueTransient(semanticObject, XbasePackage.Literals.XINSTANCE_OF_EXPRESSION__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XbasePackage.Literals.XINSTANCE_OF_EXPRESSION__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXRelationalExpressionAccess().getXInstanceOfExpressionExpressionAction_1_2_0_0_0(), semanticObject.getExpression());
		feeder.accept(grammarAccess.getXRelationalExpressionAccess().getTypeJvmTypeReferenceParserRuleCall_1_2_1_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
}
