/*
 * generated by Xtext
 */
package org.jnario.xbase.richstring.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.jnario.xbase.richstring.ui.internal.XbaseWithRichstringActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XbaseWithRichstringExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XbaseWithRichstringActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XbaseWithRichstringActivator.getInstance().getInjector(XbaseWithRichstringActivator.ORG_JNARIO_XBASE_RICHSTRING_XBASEWITHRICHSTRING);
	}
	
}
